### ISSUE TITLE
Broken build with NodeJS v7.7 (but works fine with v7.6)

### ISSUE THREAD

**Issue by nickarnold** [oracle/node-oracledb#636]
Compilation of the module fails when running the latest NodeJS v7.7 (using official installer), but works perfectly when running NodeJS v7.6. This is occuring inside of a docker container whose Dockerfile simply specified `FROM node:7.6` while things were working and `FROM node:7.7` when I got the error below during the dockerfile's npm install step. No other changes were made to the Dockerfile when the error below occurred, so I'm fairly confident this is actually a problem. 

1. What error(s) you are seeing?
```
make: Entering directory '/usr/src/app/node_modules/oracledb/build'
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o
In file included from ../src/njs/src/njsOracle.cpp:51:0:
/home/app/.node-gyp/7.7.0/include/node/node.h:44:33: fatal error: tracing/trace_event.h: No such file or directory
 #include "tracing/trace_event.h"
                                 ^
compilation terminated.
oracledb.target.mk:120: recipe for target 'Release/obj.target/oracledb/src/njs/src/njsOracle.o' failed
make: Leaving directory '/usr/src/app/node_modules/oracledb/build'
make: *** [Release/obj.target/oracledb/src/njs/src/njsOracle.o] Error 1
```

What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
`npm install`

**Comment by ecowden** [comment]
I suspect that this is likely related to a known bug in Node `v7.7.0` which breaks all native modules. More info in the [release notes](https://nodejs.org/en/blog/release/v7.7.0/).

**Comment by nickarnold** [comment]
Yep that looks like the issue. I'll close this and we'll wait for the Node team to fix that.

**Comment by cjbj** [comment]
This was also reported to [NAN](https://github.com/nodejs/nan/issues/644). "(tl;dr: It’s Node’s fault and 7.7.1 will be out with a fix soon)"

**Comment by cjbj** [comment]
(I like NAN's 'notmy_fault' issue-lable'
