### ISSUE TITLE
Debug build on Windows 7 / oracle client 12.1.0.2.0 fails

### ISSUE THREAD

**Issue by qmagpie** [oracle/node-oracledb#378]
Release build works fine on my machine.
But if I try to build a debug version:
1) node-gyp configure --debug
works ok
2) node-gyp build --debug
causes an error:
...\node_modules\oracledb\src\njs\src\njsUtils.h(73): error C2365: 'DATA_BLOB' : redefinition; previous definition was 'typedef' [...\node_modules\oracledb\build\oracledb.vcxproj]
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\wincrypt.  h(994) : see declaration of 'DATA_BLOB'

**Comment by cjbj** [comment]
Where are you running this command?  I'd guess you are in the source directory.  Did you try 'npm install --debug oracledb'  or 'npm install --debug <path_to_node-oracledb>'?

**Comment by qmagpie** [comment]
I was in the directory:
...my project...\node_modules\oracledb

But even: 'npm install --debug oracledb' in my project's root causes the same build error. And 'npm install oracledb' works fine.

**Comment by kubo** [comment]
IMO, it will be fixed by changing [binding.gyp](https://github.com/oracle/node-oracledb/blob/v1.7.1/binding.gyp#L138-L140) as follows.
```Json
                    "PreprocessorDefinitions": [
                      "WIN32_LEAN_AND_MEAN",
                      "NOCRYPT"
                    ],
```

`DATA_BLOB` is defined in [njsUtils.h](https://github.com/oracle/node-oracledb/blob/v1.7.1/src/njs/src/njsUtils.h#L62-L73). However it conflicts with `DATA_BLOB` type defined in `wincript.h` included by `windows.h`.
```C
typedef struct _CRYPTOAPI_BLOB {
                            DWORD   cbData;
    __field_bcount(cbData)  BYTE    *pbData;
} CRYPT_INTEGER_BLOB, *PCRYPT_INTEGER_BLOB,
CRYPT_UINT_BLOB, *PCRYPT_UINT_BLOB,
CRYPT_OBJID_BLOB, *PCRYPT_OBJID_BLOB,
CERT_NAME_BLOB, *PCERT_NAME_BLOB,
CERT_RDN_VALUE_BLOB, *PCERT_RDN_VALUE_BLOB,
CERT_BLOB, *PCERT_BLOB,
CRL_BLOB, *PCRL_BLOB,
DATA_BLOB, *PDATA_BLOB,
CRYPT_DATA_BLOB, *PCRYPT_DATA_BLOB,
CRYPT_HASH_BLOB, *PCRYPT_HASH_BLOB,
CRYPT_DIGEST_BLOB, *PCRYPT_DIGEST_BLOB,
CRYPT_DER_BLOB, *PCRYPT_DER_BLOB,
CRYPT_ATTR_BLOB, *PCRYPT_ATTR_BLOB;
```
By setting `NOCRYPT`,  `windows.h` doesn't include `wincript.h` and the conflict will be resolved.

Well, I have not tested it and I could not imagine the reason why release build works.

**Comment by qmagpie** [comment]
Adding NOCRYPT to PreprocessorDefinitions in binding.gyp did not work for me. 

It seems, the define WIN32_LEAN_AND_MEAN already excludes the cryptography API.
The problem may be in cooperation node-gyp & visual studio. If I manually supply in the node-gyp generated project
1) define WIN32_LEAN_AND_MEAN
2) path to oci.lib
=> debug build works

**Comment by kubo** [comment]
> It seems, the define WIN32_LEAN_AND_MEAN already excludes the cryptography API.

Ah, you are correct.

**Comment by cjbj** [comment]
Sounds like you have a workaround?
In general I don't recommend building in the source directory.

**Comment by qmagpie** [comment]
Yes. I have now a workaround. I can debug on windows now.

**Comment by kubo** [comment]
This is a bug in [binding.gyp](https://github.com/oracle/node-oracledb/blob/master/binding.gyp).
`Debug` must be under `configurations` as follows:
```C
        "OS=='win'", {
            ...
            "configurations" : {
                "Release" : {
                    ...
                },
                "Debug" : {
                    ....
                },
            }
        }
 ```
However `Debug` has been under `OS=='win'` as follows. As a result, settings inside `Debug` has no effect.
```C
        "OS=='win'", {
            ...
            "configurations" : {
                "Release" : {
                    ...
                }
            },
            "Debug" : {
                ....
            }
        }
 ```

**Comment by qmagpie** [comment]
Yes, you are right. This is the clean solution. I haven't noticed it. Thank you Kubo!

**Comment by cjbj** [comment]
Well spotted @kubo

**Comment by cjbj** [comment]
Fixed in 1.8
